### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/net.sourceforge.btanks#1]
In order to show up on the [apps page](https://beta.flathub.org/apps) this needs at least a 64x64 icon.

**Comment by garrett** [comment]
If the icon is indeed supposed to be sketchy, I used a bit of AI to "enhance" / up-rez the icon currently used on Flathub (as found in the project's sourcecode).

![icon-128](https://user-images.githubusercontent.com/10246/55818217-68e7ff00-5af6-11e9-8d54-872b74871b98.png)

![icon-64](https://user-images.githubusercontent.com/10246/55818225-6dacb300-5af6-11e9-8460-13825bbbbe78.png)

**Comment by lionirdeadman** [comment]
@whoozle I notice you're on GitHub so I thought I'd ask since I believe you're the original author of this icon.

What do you think of these upscaled icons? Should we use them to show the application in Flathub application page? Do you want them upstreamed?

I hope this isn't inappropriate.

**Comment by whoozle** [comment]
Unfortunately all original assets are long gone, if it's not in data/tiles, then it's nowhere to be found, I'm really sorry about it. :(

**Comment by whoozle** [comment]
FYI original missile tiles are 64x64, so maybe you can get it from there, nuke is missile04.png

**Comment by lionirdeadman** [comment]
That's unfortunate to hear, it would've been really cool to have the original icon!

Missile04 unfortunately is around 32px after cropping it like the application icon.

I can skip the check for 64x64 application icon or use the upscaled version of the application icon. Which would you prefer?

**Comment by whoozle** [comment]
I guess default upscale will blur everything out, I think icon upscaled by AI is looking really nice! Thanks

**Comment by lionirdeadman** [comment]
Thanks a lot for your input! Will use that.

This issue will be fixed with #4
